### ISSUE TITLE
Not notify when a new post was created

### ISSUE THREAD

**Issue by iamapinan** [tpokorra/flarum-ext-post-notification#4]
flarum version 0.1.0-beta.8.1
use latest version of extension
no notification receive when a new post created.

I already add configuration to database.

**Comment by tpokorra** [comment]
Sorry, I did not have the time to adjust for Flarum 0.1.0-beta.8

I have now fixed it for Flarum 0.1.0-beta.9 with this commit: https://github.com/tpokorra/flarum-ext-post-notification/commit/27d428662788632409236557f01c16869f006b23
